CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tickets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  submitting_user_id INT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'open',
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_tickets_users FOREIGN KEY (submitting_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ticket_id INT NOT NULL,
  user_id INT NULL,
  commenter_name VARCHAR(255) NOT NULL,
  comment_body TEXT NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_comments_tickets FOREIGN KEY (ticket_id) REFERENCES tickets(id),
  CONSTRAINT fk_comments_users FOREIGN KEY (user_id) REFERENCES users(id)
);

INSERT INTO users (username, password)
SELECT 'demo', '$2y$12$C5sY7Xztg0hefhzEHL.RFuoeYDNZspm4Z3NpwnOWcY5w2JiyjoU7K'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'demo');
